### ISSUE TITLE
Login on different device

### ISSUE THREAD

**Issue by fdietze** [social-protocols/propolis#10]
The account page shows the secret and lets one log in with another valid secret (set the cookie). Valid secrets are only generated by the server.

There should also be an easy way to log in on other devices, for example using a QR code. Or sharing a login-link.

**Comment by MHOOO** [comment]
Should we replace the existing cookie or rather just add a "link" between two secrets? I was thinking of an extra table which relates one cookie to another, effectively making statement votes be per-device instead of per-user.
In any case, I've added an options page with a rudimentary form to support this or other ways with https://github.com/social-protocols/propolis/pull/12

**Comment by fdietze** [comment]
What would be the advantage to have votes per device?

**Comment by fdietze** [comment]
We could also merge the two accounts, then no voting data is lost.

**Comment by MHOOO** [comment]
> What would be the advantage to have votes per device?

The advantages I see are:
* no destructive merging required
* later unlinking is possible, in case it was a mistake
* it is "more secure" in a way, since we could issue a warning / acceptance request on the other device about the linkage

Disadvantages:
* SQL queries would have to join all linked devices together, to get the users' votes

**Comment by fdietze** [comment]
I see. Then I'm for treating the user secret as login credentials for a specific account. And if I want to use a different device, I just log in with the same account there.

That simplifies vote management in the backend.

**Comment by MHOOO** [comment]
OK, in that case, I'll implement the following:
* Changing of the secret via the options dialog, this will...
  * check that the new secret exists
  * confirm an (optional) merge operation; show what will be migrated
  * delete the old secret with all associated data
  * switch to the new secret
* in addition, the qr-code will do the same

**Comment by fdietze** [comment]
Looks good to me :+1:

**Comment by MHOOO** [comment]
Implemented in https://github.com/social-protocols/propolis/pull/26
